In [2]:
import pandas as pd

In [3]:
konjunkturklockan = pd.read_csv("../CSV-files/konjunkturklockan.csv")
konjunkturklockan.head()

               indikator;tabellinnehåll;månad;Värde
0  BNP-indikator månad;Konjunkturläge;2000M01;-1.07
1  BNP-indikator månad;Konjunkturläge;2000M02;-0.84
2  BNP-indikator månad;Konjunkturläge;2000M03;-0.59
3  BNP-indikator månad;Konjunkturläge;2000M04;-0.29
4   BNP-indikator månad;Konjunkturläge;2000M05;0.01

In [6]:
fruktbarhet_kommun = pd.read_csv("../CSV-files/FertilitetPerKommun.csv")
fruktbarhet_kommun.head()

   region;kön;tabellinnehåll;år;Värde
0  Upplands Väsby;män;Antal;2000;1.43
1  Upplands Väsby;män;Antal;2001;1.52
2  Upplands Väsby;män;Antal;2002;1.51
3  Upplands Väsby;män;Antal;2003;1.64
4  Upplands Väsby;män;Antal;2004;1.56

In [9]:
fruktbarhet_rike = pd.read_csv("../CSV-files/Fruktbarhet_riket.csv")
fruktbarhet_rike.head()

     region  kön    år  Summerad fruktsamhet, antal
0  00 Riket  män  2000                         1.42
1  00 Riket  män  2001                         1.44
2  00 Riket  män  2002                         1.52
3  00 Riket  män  2003                         1.57
4  00 Riket  män  2004                         1.61

In [16]:
befolkning_tathet = pd.read_csv("../CSV-files/befolkningstathet.csv")
befolkning_tathet.head()

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 13: invalid continuation byte