In [1]:
import pandas as pd

In [3]:
konjunkturklockan = pd.read_csv("../CSV-files/konjunkturklockan.csv")
konjunkturklockan.head()

               indikator;tabellinnehåll;månad;Värde
0  BNP-indikator månad;Konjunkturläge;2000M01;-1.07
1  BNP-indikator månad;Konjunkturläge;2000M02;-0.84
2  BNP-indikator månad;Konjunkturläge;2000M03;-0.59
3  BNP-indikator månad;Konjunkturläge;2000M04;-0.29
4   BNP-indikator månad;Konjunkturläge;2000M05;0.01

In [4]:
fruktbarhet = pd.read_csv("../CSV-files/scb_data.csv")
fruktbarhet.head()

   region;kön;tabellinnehåll;år;Värde
0  Upplands Väsby;män;Antal;2000;1.43
1  Upplands Väsby;män;Antal;2001;1.52
2  Upplands Väsby;män;Antal;2002;1.51
3  Upplands Väsby;män;Antal;2003;1.64
4  Upplands Väsby;män;Antal;2004;1.56